import { BaseEntity } from './../../shared';

export class Distributor implements BaseEntity {
    constructor(
        public id?: number,
        public idDistributor?: number,
        public nama?: string,
        public status?: number,
        public kodeId?: string,
        public pin?: string,
        public com?: string,
        public noKontak?: string,
        public metode?: string,
        public kodeParsing?: string,
        public kodeParsing2?: string,
        public replyno?: string,
        public tglInput?: any,
        public userInput?: string,
        public tglUpdate?: any,
        public userUpdate?: string,
        public ip?: string,
        public isvre?: number,
        public isgtw?: number,
        public ugtw?: string,
        public isfilter?: number,
        public parseSaldo?: string,
        public parseHarga?: string,
        public tiketWrap?: string,
        public istiketsend?: number,
        public pesanTiket?: string,
        public saldoSupwarn?: number,
        public issortby?: number,
        public parseUnit?: string,
        public isulangim?: number,
        public ishlr?: number,
        public kodeParsing3?: string,
        public idHistory?: number,
        public kodeParsing4?: string,
        public selisihSupwarn?: number,
        public timeon?: string,
        public timeoff?: string,
    ) {
    }
}
