import { BaseEntity } from './../../shared';

export class Member implements BaseEntity {
    constructor(
        public id?: number,
        public idMember?: string,
        public tglRegister?: any,
        public nama?: string,
        public alamat?: string,
        public pin?: string,
        public status?: number,
        public saldo?: number,
        public idUpline?: string,
        public kodeLevel?: string,
        public tglInput?: any,
        public userInput?: string,
        public tglUpdate?: any,
        public userUpdate?: string,
        public idMaster?: string,
        public rptTrx?: number,
        public selisih?: number,
        public counter?: number,
        public dongleNo?: string,
        public head2head?: number,
        public ymid?: string,
        public iprpt?: string,
        public lastTrx?: any,
        public ref?: string,
        public crypt?: string,
        public gtalkid?: string,
        public vremsgid?: string,
        public kodepos?: string,
        public iswarn?: number,
        public msnid?: string,
        public idlogsal?: number,
        public lastKodetrx?: number,
        public lastIdtrx?: number,
        public telebotid?: string,
        public telegramid?: string,
        public isowner?: number,
        public cryptowner?: string,
        public pinowner?: string,
        public memberHps?: BaseEntity[],
    ) {
    }
}
